### ISSUE TITLE
Status of this ? Place to start to contribute ?

### ISSUE THREAD

**Issue by cyrilchapon** [geodatagouv/wfs-client#2]
Interested in building a stronger solution than existing ones, this repos seems to be the best one for this.

What is the status, is that abandonned ? Especially about `getFeatures` support

Where to start, if I could help ?

As a start, and of my experience about javascript - geojson stuff, here are some libs :

- https://www.npmjs.com/package/gjtk very stable geojson type-checking lib (useful for tests)
- https://github.com/tmcw/awesome-geojson collection of awesome stuff regarding geojson
- https://github.com/mapbox/geojsonhint hint geojson against the spec
- http://turfjs.org/ the famous turf.js (the interesting part of the lib for a wfs client is not the "manipulation" stuff, but more the utils, for example it can help construct GeoJSON objects very efficiently)
- https://github.com/axios/axios a wonderful trade for superagent (more error-friendly, but less test-friendly)

**Comment by jdesboeufs** [comment]
We currently use this tool to extract metadata from WFS services, and GDAL to extract features.
But we have plan to drop GDAL to have more control on the operation.

The first thing to do is to write a GML parser, probably based on `sax`.
Indeed the target format should be GeoJSON ;)

If you are near Paris, we can lunch and talk one of these days!

**Comment by jdesboeufs** [comment]
And no this repos is not abandonned as it's a core feature of geo.data.gouv.fr, which need severe improvements ;)

**Comment by tusbar** [comment]
Feel free to contribute, PRs are always welcome. ❤️
